```{r}
library(dplyr)
library(purrr)
library(ggplot2)
```

data cleaning!
```{r}
hist_mar <- read.csv('historical_marathon_dataset.csv')
hist_mar$gender <- as.factor(hist_mar$gender)

# country has lots of levels for US and typo for Australia
hist_mar$country[hist_mar$country == "Aus"] <- "Australia"
hist_mar$country[hist_mar$country == "Australaia"] <- "Australia"
hist_mar$country[hist_mar$country == "US"] <- "USA"
hist_mar$country[hist_mar$country == "United States"] <- "USA"
hist_mar$country[is.na(hist_mar$country)] <- "Unkown"
hist_mar$country <- as.factor(hist_mar$country)

# shoe brand has some typos, and encode NA's as a new class
hist_mar$shoe_brand[hist_mar$shoe_brand == "Addas"] <- "Adidas"
hist_mar$shoe_brand[is.na(hist_mar$shoe_brand)] <- "Unkown"
hist_mar <- hist_mar %>%
  mutate(shoe_brand = str_trim(shoe_brand))
hist_mar$shoe_brand <- as.factor(hist_mar$shoe_brand)

# remove negative observations in weekly_km
hist_mar <- hist_mar[hist_mar$weekly_km >= 0, ]

# properly encode boolean features
hist_mar <- hist_mar %>%
  mutate(across(c(injured_prev_mth, injured_prev_qtr, injured_prev_hy), as.logical))

event_summary <- read.csv('event_summary.csv')
event_summary <- event_summary %>%
  mutate(across(c(gel_support, stretching_station, music_at_start), as.logical))

data <- hist_mar %>%
  left_join(event_summary, by = "year")

data$needed_med <- !is.na(data$medical_km_bin)
hist_mar$needed_med <- !is.na(hist_mar$medical_km_bin)
```



Plots of variables over time

```{r}
# proportion of needed medical attention
proportion_df <- data %>%
  group_by(year) %>%
  summarise(prop_needed_med = mean(needed_med, na.rm = TRUE)) %>%
  ungroup()

ggplot(proportion_df, aes(x = year, y = prop_needed_med)) +
  geom_line(color = "firebrick", size = 1) +
  geom_point(color = "firebrick") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Runners Needing Medical Attention by Year",
       x = "Year",
       y = "Proportion of TRUE 'needed_med'") +
  theme_minimal()


# number of incidents
summary_df <- data %>%
  filter(needed_med == TRUE) %>%
  group_by(year) %>%
  summarise(count = n()) %>%
  ungroup()

ggplot(summary_df, aes(x = year, y = count)) +
  geom_col(fill = "steelblue") +
  labs(title = "Number of Incidents by Year",
       x = "Year",
       y = "Count of TRUE 'needed_med'") +
  theme_minimal()

# proportion of genders
gender_props <- data %>%
  filter(gender %in% c("Male", "Female")) %>% 
  group_by(year, gender) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(year) %>%
  mutate(proportion = count / sum(count)) %>%
  ungroup()

ggplot(gender_props, aes(x = year, y = proportion, fill = gender)) +
  geom_col(position = "stack") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Male and Female by Year",
       x = "Year",
       y = "Proportion",
       fill = "Gender") +
  theme_minimal()

# avg weight
avg_weight_by_year <- data %>%
  group_by(year) %>%
  summarise(avg_weight = mean(weight, na.rm = TRUE)) %>%
  ungroup()

ggplot(avg_weight_by_year, aes(x = year, y = avg_weight)) +
  geom_line(color = "darkgreen", size = 1) +
  geom_point(color = "darkgreen") +
  labs(title = "Average Weight by Year",
       x = "Year",
       y = "Average Weight") +
  theme_minimal()


# avg weekly km
avg_weekly_by_year <- data %>%
  group_by(year) %>%
  summarise(avg_weekly_km = mean(weekly_km, na.rm = TRUE)) %>%
  ungroup()

ggplot(avg_weekly_by_year, aes(x = year, y = avg_weekly_km)) +
  geom_line(color = "darkgreen", size = 1) +
  geom_point(color = "darkgreen") +
  labs(title = "Average Weekly KM",
       x = "Year",
       y = "Average Weekly KM") +
  theme_minimal()

# avg pb
avg_pb_by_year <- data %>%
  group_by(year) %>%
  summarise(avg_pb = mean(personal_best, na.rm = TRUE)) %>%
  ungroup()

ggplot(avg_pb_by_year, aes(x = year, y = avg_pb)) +
  geom_line(color = "darkgreen", size = 1) +
  geom_point(color = "darkgreen") +
  labs(title = "Average PB",
       x = "Year",
       y = "Average PB") +
  theme_minimal()

## ok it looks decent for the predictors

variables <- c("rainfall", "temp_10am", "humidity", "elevation_gain",
               "hydration_stations", "toilet_stations", "crowding_density",
               "newsletter_registration")

for (var in variables) {
  p <- ggplot(event_summary, aes(x = year, y = .data[[var]])) +
    geom_line(color = "steelblue", size = 1) +
    geom_point(color = "steelblue") +
    labs(title = paste("Yearly", var),
         x = "Year",
         y = var) +
    theme_minimal()
  
  print(p)
}


```

Compare historical data to this years data

```{r}
data_2025 <- read.csv('2025_marathon_data.csv')
data_2025$gender <- as.factor(data_2025$gender)

# country has lots of levels for US and typo for Australia
data_2025$country[data_2025$country == "Aus"] <- "Australia"
data_2025$country[data_2025$country == "Australaia"] <- "Australia"
data_2025$country[data_2025$country == "US"] <- "USA"
data_2025$country[data_2025$country == "United States"] <- "USA"
data_2025$country[is.na(data_2025$country)] <- "Unkown"
data_2025$country <- as.factor(data_2025$country)

# shoe brand has some typos, and encode NA's as a new class
data_2025$shoe_brand[data_2025$shoe_brand == "Addas"] <- "Adidas"
data_2025$shoe_brand[is.na(data_2025$shoe_brand)] <- "Unkown"
data_2025 <- data_2025 %>%
  mutate(shoe_brand = str_trim(shoe_brand))
data_2025$shoe_brand <- as.factor(data_2025$shoe_brand)

# remove negative observations in weekly_km
data_2025 <- data_2025[data_2025$weekly_km >= 0, ]

# properly encode boolean features
data_2025 <- data_2025 %>%
  mutate(across(c(injured_prev_mth, injured_prev_qtr, injured_prev_hy), as.logical))



summary(hist_mar)

summary(data_2025)

```

```{r}
hist(hist_mar$marathons_xp)
hist(data_2025$marathons_xp)

sum(hist_mar$marathons_xp == 0) / nrow(hist_mar)
sum(data_2025$marathons_xp == 0) / nrow(data_2025)
```





